import JSZip from 'jszip';
import {
    TERRARIA_KEYS,
    DEFAULT_TERRARIA_VERSION,
    buildTerrariaHjson,
    buildBuildTxt,
    buildModSource,
    buildCsproj,
} from './terrariaExportData.js';
/**
 * Compile and trigger download of the Terraria tModLoader localization pack ZIP.
 */
export const exportTerrariaLocalizationPack = async (config, customTranslations, options = {}) => {
    const {
        modName = 'MyConlangMod',
        langCode = 'en-US',
        modVersion = '1.0.0',
        modAuthor = config.conlangName || 'Conlang Author',
        gameVersion = DEFAULT_TERRARIA_VERSION,
        homepage = 'https://tmodloader.net/',
    } = options;

    const zip = new JSZip();
    const conlangName = config.conlangName || 'My Conlang';

    // 1. Localization/<code>.hjson — vanilla overrides at the root.
    const hjsonContent = buildTerrariaHjson(customTranslations, { modName, gameVersion });
    zip.folder('Localization').file(`${langCode}.hjson`, hjsonContent);

    // 2. Mod manifest + source, so this is a buildable mod.
    zip.file('build.txt', buildBuildTxt({
        displayName: conlangName,
        author: modAuthor,
        modVersion,
        homepage,
    }));
    zip.file(`${modName}.cs`, buildModSource(modName));
    zip.file(`${modName}.csproj`, buildCsproj(modName));

    // 3. description.txt, recording the targeted game version.
    zip.file('description.txt',
        `${conlangName} Language Localization\n\n` +
        `Translates Terraria ${gameVersion} content into ${conlangName}.\n` +
        `Language file: ${langCode}.hjson\n` +
        `Generated by Conlang Engine.\n`);

    // 4. Download
    const content = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(content);
    const safeName = conlangName.replace(/\s+/g, '_').toLowerCase();
    const a = document.createElement('a');
    a.href = url;
    a.download = `Terraria_${gameVersion}_Localization_${safeName}.zip`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};
